Switching three.js repo to three to fix build issues
In the beginning there was only one npm package for three.js, called
`three` as in `npm install three`. It's maintained by @bhouston.
Recently @mrdoob added a new npm module that he maintains, called
`three.js`, as in `npm install three.js`. This react-three-renderer
repository uses the newer `three.js`. However, the newer `three.js` npm
package is broken and contains invalid javascript, which will break any
build using a webpack/browserify/etc build compilation step with
something like:

    if ( self.requestAnimationFrame === undefined || self.cancelAnimationFrame === undefined  ) {
            ^
        ReferenceError: self is not defined

This ripples down into users of this react-three-renderer repository
because we are forced to use `three.js` to make our prop types the same.
For instance, new THREE.Vector3() passed as a prop from user land (using
`three`) will fail in this repo, because it's a different THREE object than
`three.js`.

The quick fix is to use the older, more mature, and functional `three`
npm package for now.

See https://github.com/mrdoob/three.js/issues/7800 for the full story.